berinhard/model_mommy

.travis.yml
I noticed that the Travis badge was showing an error, and it seems that was due to pip timing out on one of the builds. I've run into this on a couple of other projects, and have handled it there by wrapping install commands with `travis_retry` (more info on that [here](http://docs.travis-ci.com/user/build-timeouts/#Timeouts-installing-dependencies)).
I also saw that Travis is still installing Pillow, even though the tests no longer depend on it, and so I pulled that from the config file as well.
=> Minor Travis config updates

.gitignore, model_mommy/mommy.py, test/generic/tests/test_mommy.py
Now m2m related objects are created if flag `make_m2m=True` is passed together with `_fill_optional=True` or `_fill_optional="name_of_field"`
=> Issue #216

runtests.py
```
Django 1.7 changed the global defaults for the MIDDLEWARE_CLASSES. django.contrib.sessions.middleware.SessionMiddleware, django.contrib.auth.middleware.AuthenticationMiddleware, and django.contrib.messages.middleware.MessageMiddleware were removed from the defaults. If your project needs these middleware then you should configure this setting. 
```
As the project use none of these middleware, I'm passing explicity an empty tuple to django.settings in versions >= 1.7.
=> Explicit pass empty middleware classes

model_mommy/mommy.py, test/generic/models.py, test/generic/tests/test_mommy.py
we stumpled on this because one of our models has a method called `next` (from `django-orderable`) which lead to mommy assigning `None` to this attribute. 
I changed the method to find out if a thing is an iterable.
=> Fix generating models which have a 'next' method, but aren't iterators

model_mommy/__init__.py
Previous minor version was 1.2.4 at
SHA 7d01fc680ef7013a4ae68e6ea7d87c990dc55e82
Specifically the new commits would help solve this problem:
```
File "/home/vagrant/envs/--/lib/python2.7/site-packages/model_mommy/mommy.py", line 79, in make
return mommy.make(**attrs)
File "/home/vagrant/envs/--/lib/python2.7/site-packages/model_mommy/mommy.py", line 262, in make
return self._make(commit=True, **attrs)
File "/home/vagrant/envs/--/lib/python2.7/site-packages/model_mommy/mommy.py", line 312, in _make
model_attrs[field.name] = self.generate_value(field)
File "/home/vagrant/envs/--/lib/python2.7/site-packages/model_mommy/mommy.py", line 420, in generate_value
raise TypeError('%s is not supported by mommy.' % field.__class__)
TypeError: <class 'django.db.models.fields.BinaryField'> is not …
```
=> Bumping version to reflect latest.

model_mommy/generators.py
I get warnings about get_models deprecation when running tests on 1.8
=> Fix deprecation warning for get_models

model_mommy/mommy.py
Fixed `ForeignKeyTestCase.test_related_models_recipes` test for Django 1.9+
=> Fixed related recipes objects saving for django 1.9

model_mommy/mommy.py, test/generic/models.py, test/generic/mommy_recipes.py, test/generic/tests/test_recipes.py
Ensures that related models are saved before adding, using the same logic as is used for manytomany.
=> Fix related() with nullable foreignkeys on django 1.9.

docs/source/deprecation_warnings.rst, docs/source/how_mommy_behaves.rst, model_mommy/generators.py, model_mommy/mommy.py, test/generic/tests/test_filling_fields.py
`set` actually shadows a built-in function name, so I changed it to `add`.
Thinking about it a little more I have a small suggestion, we could leave the `generators.py` for mommy's own generators and add a method in the mommy module to enable the user to define custom generators.
Something like:
`from model_mommy import mommy`
`mommy.add_generator(field, gen_fun)`
`mommy.remove_generator(field)`
=> New generators register

.travis.yml, docs/source/how_mommy_behaves.rst, model_mommy/generators.py, model_mommy/random_gen.py, runtests.py, test/generic/models.py, test/generic/tests/test_filling_fields.py, tox.ini
HStoreField can be handled in the same manner as JSONField. Testing is a bit trickier since we need to install the hstore extension on the test postgres database before the models themselves are created. 
- Generator for hstore fields matching how JSONFields are currently handled.
- Updated tests to create hstore extension when needed and test hstorefield filling
- Update docs-supported fields list to include postgres specific fields
=> Add support for HStoreFields

requirements.txt, setup.py
Hi,
A small improvement: requirements, for test and installation, should be pin-pointed to supported versions to avoid problems.
The commit pin-points Django to claimed supported versions >= 1.6, < 1.11 since 1.10 support was added in version 1.3.0 and 1.5 support was dropped in version 1.3.1.
=> Pin-points supported Django versions

docs/source/basic_usage.rst, docs/source/deprecation_warnings.rst, model_mommy/mommy.py, test/generic/tests/test_filling_fields.py
Fixes #303 
@robertfw maybe you'll be interested about this PR too ;)
@vandersonmota my proposal to fix the file creation bug is the same we adopted with M2M fields. The default behaviour now is that model mommy **does not create** files for file fields. But, if the developer wants to, there is a new flag called `_create_files` he/she can pass to `mommy.make`.
Since this introduces new break changes to older versions, we'll need to add some docs on this. If you're good with my proposal, I can write it.
=> Closes #303: Clean or use temp files for FileFields

model_mommy/recipe.py
Thanks for a lovely project! I hopefully have a small improvement to contribute.
Mommy makes a database call when calling `prepare` on a recipe with a sequence. Usually, our aim when using `prepare` is to avoid database queries as they're slow. I dug into the code to find out why this call gets made, and I think it's avoidable.
--
If I'm not mistaken, the intention of this bit of code is to store a backup copy of the given iterator while being able to iterate through it for this `make()` or `prepare()` call. We need to detect if this is the first run, so we check if any instances are present or if the dictionary is empty.
This causes a problem when using `prepare()`, because it still does a call to the database - something we usually don't want when using `prepare()`. If I'm not mistaken, …
=> Avoid touching the database in prepare()

Changelog.txt
When I upgraded model_mommy, my tests that used the files created in ImageFields started to break because the field was filled with a `<ImageFieldFile: None>` instance.
`_create_files` flag is needed to use old behavior.
=> imagefield behavior

model_mommy/mommy.py
Fixes this deprecation warning:
> RemovedInDjango20Warning: Usage of ForeignObjectRel.to attribute has been deprecated. Use the model attribute instead.
Looks like it's safe to just simply change this from `.to` to `.model`, since Django 1.8 provides an alias (see [here](https://github.com/django/django/blob/1.8/django/db/models/fields/related.py#L1291)).
I should have done more extensive testing before requesting a new PyPI version. Sorry :(
=> Change `ForeignObjectRel.to` references to `ForeignObjectRel.model`

docs/source/recipes.rst
Explain the way how `make_recipe` works, which is somehow implicit in the examples but not fully clear. 
I also stripped the code a bit, to make it shorter and easier to read. Removed obvious comments
=> #340 docs: explain make_recipe

model_mommy/mommy.py, test/generic/tests/test_mommy.py
fixes #344
As described in that issue, django has two such set() methods, one with and one without the bulk parameter. model_mommy was calling the one without the parameter, and specifying it simply had no effect previously. django broke it by making the parameter list more explicit.
i couldn't get the tests running (i get a massive bunch of `django.db.utils.InterfaceError: Error binding parameter 15 - probably unsupported type.`), so there is no test and i have no idea whether that breaks anything (e.g. if in some circumstance, model_mommy uses the other type of manager which actually has that parameter), so lets see what travis says...
=> Remove wrong parameter, fixes #344

model_mommy/recipe.py, test/generic/mommy_recipes.py, test/generic/tests/test_recipes.py
If you write a subclass of Recipe, for whatever reason, calling
the extend method on it will not return the same type, but always
Recipe. It should be expected that `extend` extends the current
type and returns a new instance of the same type.
=> Fix type error -- Recipe.extend should return the same type

model_mommy/mommy.py, test/generic/tests/test_mommy.py, test/generic/tests/test_recipes.py
By default, the param `_refresh_after_create ` is `False`. If `True`, it will call `refresh_from_db` after creation.
Solves https://github.com/vandersonmota/model_mommy/issues/337. CC @jonashaag.
=> Add option to automatically call refresh_from_db

docs/source/recipes.rst, model_mommy/__init__.py, model_mommy/recipe.py, model_mommy/utils.py, test/generic/tests/test_recipes.py
Enable `seq` method to be imported directly from `model_mommy` module and improve its documentation with examples using `mommy.make`. Issue #371
=> Enable seq method to be imported directly from model_mommy

model_mommy/generators.py
BigIntegerField, BinaryField, UUIDField, DurationField, GenericIPAddressField - were introduced in older Django versions. Django 1.11 (which is the minimal we are going to support) has all of them.
=> Remove obsolete import logic in generators.py

tests/generic/models.py, tests/test_filling_fields.py
https://github.com/berinhard/model_mommy/pull/401 removed obsolete imports of old Django fields, but we still had leftovers in tests.
This PR cleans up import logic, related to BigIntegerField, BinaryField, UUIDField, DurationField, GenericIPAddressField and PostgreSQL-related fields.
Green CI covers everything.
=> Remove obsolete field imports in tests

tests/generic/models.py, tests/test_extending_mommy.py, tests/test_filling_fields.py, tests/test_mommy.py, tests/test_recipes.py, tests/test_utils.py
Since we switched to pytest in #395, it is time to use it with full force!
ToDo:
=> Get rid of `TestClass` usage (pytest FTW)

Changelog.txt, model_mommy/mommy.py, tests/generic/models.py, tests/test_mommy.py
Resolves #377 and a test for it (based on what was described).
This is a fork of @timthelion's solution (https://github.com/berinhard/model_mommy/pull/378). The tests were failing before because many to many relations doesn't have `bulk` as argument. See this [comment from the docs](https://docs.djangoproject.com/en/2.2/ref/models/relations/#django.db.models.fields.related.RelatedManager.set):
> For many-to-many relationships, the bulk keyword argument doesn’t exist.
=> Save object instances when handling one to many relations
