- test/generic/models.py
Add default=False to BooleanFileld because of behavior change since Django 1.6.
https://docs.djangoproject.com/fr/1.8/releases/1.6/#booleanfield-no-longer-defaults-to-false
> add default value to BooleanField to solve issue #222

- model_mommy/generators.py
- model_mommy/mommy.py
- test/generic/models.py
- test/generic/tests/test_filling_fields.py
> Supports DurationField

- model_mommy/mommy.py
> Fix for #202 : test contenttype as subclasss

- test/generic/tests/test_filling_fields.py
This addition in the test shows the issue fixed in patch: c4a0549bbd195574f2ac50655ea11aefbb9845f2
> Added test for pull request #233

- docs/source/how_mommy_behaves.rst
- model_mommy/mommy.py
- model_mommy/utils.py
- test/generic/generators.py
- test/generic/tests/test_filling_fields.py
- test/generic/tests/test_utils.py
Can you review this please and merge if ok or tell me whats not?
> Custom generators as strings

- model_mommy/mommy.py
- test/generic/tests/test_mommy.py
* in both make() and prepare()
> Throw InvalidQuantityException for _quantity=0

- model_mommy/generators.py
- model_mommy/mommy.py
- test/generic/models.py
- test/generic/tests/test_filling_fields.py
> Supports UUIDField

- docs/source/how_mommy_behaves.rst
- model_mommy/mommy.py
- test/generic/models.py
- test/generic/mommy_recipes.py
- test/generic/tests/test_mommy.py
- test/generic/tests/test_recipes.py
> Pass custom parameters to `save` method

- dev_requirements.txt
- docs/source/basic_usage.rst
- model_mommy/mommy.py
- test/generic/mommy_recipes.py
- test/generic/tests/test_mommy.py
- test/generic/tests/test_recipes.py
> Add _save_related flag to prepare API

- README.rst
- model_mommy/mommy.py
- test/generic/models.py
- test/generic/tests/test_mommy.py
> Closes #280

- docs/source/how_mommy_behaves.rst
> Hyper-critical zero day fix

- Makefile
- dev_requirements.txt
- setup.cfg
> Enable wheel support

- model_mommy/recipe.py
- test/generic/tests/test_recipes.py
You can call `Recipe.prepare` on a model with a ForeignKey and if
you don't have defined a `foreign_key`-recipe the related object
will not be persited. However if you define a related recipe the
related object will be persistet.
Besides that behavior being inconsistent, there really is no reason
and it presents disadvantages.
This patch solves the issue, by using the `_save_realted` attribute
that is already existing but not used for related objects in recipes.
> Recipe.prepare does not save related recipes

- Changelog.txt
We recently merged #300 which fixes `_save_related` - Adding that to Changelog
> Update docs on how to use _save_related on recipes

- docs/source/how_mommy_behaves.rst
Fixed typo in code snippet, "generatos" should be "generators"
> Fix typo in how_mommy_behaves.rst

- model_mommy/mommy.py
- test/generic/tests/test_filling_fields.py
> Fixes #310: Can't override default generator using generator.add

- README.rst
- requirements.txt
- setup.py
crate.io is now some kind of database vendor!
> Remove outdated pypi badges

- Changelog.txt
- model_mommy/__init__.py
- model_mommy/mommy.py
- model_mommy/recipe.py
- test/generic/tests/test_mommy.py
> Allow Models with an attribute named 'model' to be used in mommy.make

- docs/source/deprecation_warnings.rst
- model_mommy/__init__.py
- setup.py
> Version bump

- model_mommy/generators.py
- model_mommy/gis.py
- model_mommy/random_gen.py
- runtests.py
- test/generic/models.py
- test/generic/tests/test_filling_fields.py
- tox.ini
This fixes #256 and would make GeoDjango users very happy.
> Support GIS fields when django.contrib.gis is in INSTALLED_APPS

- docs/source/how_mommy_behaves.rst
GIS fields are supported but it's not mentioned in docs.
> Updated docs with GIS supported fields.

- model_mommy/mommy.py
See https://github.com/vandersonmota/model_mommy/issues/367#issuecomment-398152478 for more info.
> Use default value for unknown field types

- model_mommy/mommy.py
- tests/test_mommy.py
Solution for issue #373 . Just checking for possible _fill_optional input and throwing an error. tests added. Though i don't know your iterator checking policy - i am checking only basic iterables.
> Validate _fill_optional 

- docs/source/basic_usage.rst
- docs/source/how_mommy_behaves.rst
This PR adds documentation for #396 and #405.
> Add documentation on the missing PRs
